# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e34562f25ff3ea8a89d197e455e95d64cb711d2536eff2bd459f0a57440d97deaaf7f541f3c59c91c24785780de5aa36a7aa67b9e4ff5a6e2b17038a4d42257

test:
  secret_key_base: 4e839799bfdf0bfbe0c25fe2655735eda9cdc781e39d1249b8b879bab9acf827148d6f22679272d10adbb44ca76e2c36c481f75f14150f1bd2bf3cdb8309b9ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
